cabal-version: 3.14
name: lib-web
version: 0.1.0.0
build-type: Simple

library
  hs-source-dirs: src
  exposed-modules:
    Cahier.Web.Logger
    Cahier.Web.Presenters.Blog
    Cahier.Web.Presenters.Pages
    Cahier.Web.Presenters.Poetry
    Cahier.Web.Templates.Blog.Index
    Cahier.Web.Templates.Blog.Show
    Cahier.Web.Templates.Layout
    Cahier.Web.Templates.NotFound
    Cahier.Web.Templates.Pages.About
    Cahier.Web.Templates.Pages.Home
    Cahier.Web.Templates.Poetry.Index
    Cahier.Web.Templates.Poetry.Show

  build-depends:
    base >=4.21 && <5,
    blaze-html >=0.9.2 && <0.10,
    bytestring >=0.12.2 && <0.13,
    fast-logger >=3.2.6 && <3.3,
    http-types >=0.12.4 && <0.13,
    cahier-content,
    network >=3.2.8 && <3.3,
    shakespeare >=2.1.7 && <2.2,
    text >=2.1.2 && <2.2,
    time >=1.14 && <1.15,
    wai >=3.2.4 && <3.3,
    wai-extra >=3.1.18 && <3.2,

  default-extensions:
    OverloadedStrings
    QuasiQuotes

  default-language: GHC2024

test-suite web-tests
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  other-modules:
    Web.LoggerTest

  build-depends:
    base >=4.14 && <5,
    http-types >=0.12.4 && <0.13,
    lib-web,
    network >=3.2.8 && <3.3,
    silently,
    tasty >=1.4 && <2,
    tasty-hunit >=0.10 && <0.11,
    wai >=3.2.4 && <3.3,
    wai-extra >=3.1.18 && <3.2,

  default-extensions:
    OverloadedStrings

  default-language: GHC2024
