cabal-version: 3.14
name: lib-web
version: 0.1.0.0
build-type: Simple

library
  hs-source-dirs: src
  exposed-modules:
    Cahier.Web.Presenters.Blog
    Cahier.Web.Presenters.Pages
    Cahier.Web.Presenters.Poetry
    Cahier.Web.Templates.Blog.Index
    Cahier.Web.Templates.Blog.Show
    Cahier.Web.Templates.Layout
    Cahier.Web.Templates.NotFound
    Cahier.Web.Templates.Pages.About
    Cahier.Web.Templates.Pages.Home
    Cahier.Web.Templates.Poetry.Index
    Cahier.Web.Templates.Poetry.Show
    Cahier.Web.Url

  build-depends:
    base >=4.21 && <5,
    blaze-html >=0.9.2 && <0.10,
    lib-core,
    shakespeare >=2.1.7 && <2.2,
    text >=2.1.2 && <2.2,
    time >=1.14 && <1.15,

  default-extensions:
    OverloadedStrings
    QuasiQuotes

  default-language: GHC2024

test-suite web-tests
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  other-modules:
    Web.UrlTest

  build-depends:
    base >=4.14 && <5,
    lib-web,
    tasty >=1.4 && <2,
    tasty-hunit >=0.10 && <0.11,

  default-language: GHC2024

test-suite cahier-doctest
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Doctest.hs
  build-depends:
    base >=4.14 && <5,
    doctest >=0.22,

  default-language: GHC2024
